preset: laravel
risky: true
version: 7

disabled:
  - concat_without_spaces
  - not_operator_with_successor_space

enabled:
  - is_null
  - dir_constant
  - phpdoc_property
  - logical_operators
  - concat_with_spaces
  - phpdoc_add_missing_param_annotation
