preset: laravel
risky: true
version: 7

disabled:
  - concat_without_spaces
  - not_operator_with_successor_space
  - laravel_phpdoc_order
  - laravel_phpdoc_separation

enabled:
  - is_null
  - dir_constant
  - phpdoc_order
  - phpdoc_property
  - phpdoc_separation
  - logical_operators
  - concat_with_spaces
  - phpdoc_add_missing_param_annotation
