preset: laravel

disabled:
  - alpha_ordered_imports
  - concat_without_spaces
  - not_operator_with_successor_space

enabled:
  - is_null
  - phpdoc_order
  - phpdoc_property
  - phpdoc_separation
  - logical_operators
  - concat_with_spaces
  - length_ordered_imports
  - phpdoc_add_missing_param_annotation
